spring:
  application:
    name: library-server
  jpa:
    open-in-view: false
  jackson:
    default-property-inclusion: non_null

server:
  port: 8443
  servlet:
    context-path: /library
  error:
    include-stacktrace: never
  ssl:
    enabled: true
    key-store: classpath:server-keystore.p12
    key-store-type: PKCS12
    key-store-password: changeit
    key-password: changeit
    trust-store: classpath:pparker-trust.p12
    trust-store-password: changeit
    client-auth: need

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    web:
      exposure:
        include: '*'

info:
  application:
    name: library-server
    version: 1.0.0

logging:
  level:
    org.springframework.security: debug
